version: '3.3'

services:
  postgres:
    image: postgres:latest
    container_name: testing
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432